const skillGroups=[
{t:'Lenguajes y marcado',f:['Java.svg','C.svg','C++ (CPlusPlus).svg','C# (CSharp).svg','Embedded C.svg','Cobol.svg','Dart.svg','HTML5.svg','CSS3.svg','JavaScript.svg','jQuery.svg','Kotlin.svg','PHP.svg','Pascal.svg','Python.svg','R.svg','Ruby.svg','Rust.svg','Scala.svg','Swift.svg','TypeScript.svg','Visual Basic.svg','JSON.svg','LaTeX.svg','TeX.svg']},
{t:'Bases de datos, búsqueda y streaming',f:['MySQL.svg','Mariadb.svg','PostgresSQL.svg','Microsoft SQL Server.svg','Oracle.svg','MongoDB.svg','Neo4j.svg','SQLite.svg','Microsoft Office Access.svg','DBeaver.svg','SQL Developer.svg','Redis.svg','Couchbase.svg','Aws dynamodb.svg','Aws keyspaces.svg','Sybase.svg','Elastic search.svg','Elastic stack.svg','Kibana.svg','Kafka.svg','Apache Apex.svg']},
{t:'Arquitectura, APIs y metodologías',c:[['HEX','Arquitectura hexagonal'],['µS','Microservicios'],['MVC','Modelo Vista Controlador'],['REST','API REST'],['SCR','Scrum']]},
{t:'Frameworks, APIs y desarrollo',f:['Angular.svg','AngularJS.svg','React.svg','Node.js.svg','Spring.svg','Spring boot.svg','Hibernate.svg','GWT.svg','Symfony.svg','Tailwind CSS.svg','Flutter.svg','Ionic.svg','NET core.svg','JUnit.svg','Mockito.svg','Apache Maven.svg','Gradle.svg','Apache Tomcat.svg','Firebase.svg','Postman.svg','OpenGL.svg','Openclaw.svg','Matter.svg','Salesforce.svg','Odoo_logo.svg']},
{t:'DevOps, nube y repositorios',f:['Git.svg','GitHub.svg','GitHub Actions.svg','GitHub Codespaces.svg','GitLab.svg','Docker.svg','Kubernetes.svg','Jenkins.svg','AWS.svg','Google Cloud.svg','Microsoft Azure.svg']},
{t:'IDEs, motores y editores',f:['IntelliJ IDEA.svg','Eclipse IDE.svg','Visual Studio Code (VS Code).svg','Visual Studio.svg','Android Studio.svg','Cursor.svg','Vim.svg','Godot Engine.svg','Unreal Engine.svg','Unity.svg','Apache NetBeans.svg','Adobe Dreamweaver CC.svg']},
{t:'Sistemas, virtualización y terminales',f:['Linux.svg','Debian.svg','Ubuntu.svg','Fedora.svg','Red Hat.svg','Gentoo.svg','Open SUSE.svg','Mint.svg','Windows 11.svg','MS-DOS.svg','Powershell.svg','Raspberry Pi.svg','Android.svg','VirtualBox.svg','Vmware workstation.svg']},
{t:'Diseño, documentación, colaboración y ofimática',f:['Adobe Acrobat DC.svg','Adobe Illustrator.svg','Adobe Photoshop.svg','Adobe InDesign CC.svg','Canva.svg','Figma.svg','GIMP.svg','Microsoft Office Excel.svg','Microsoft Office Word.svg','Microsoft Office PowerPoint.svg','Microsoft Office OneNote.svg','Microsoft Office Teams.svg','Microsoft OneDrive.svg','Google Drive.svg','Slack.svg']},
{t:'IA, web y recursos',f:['ChatGPT.svg','Claude.svg','Claude code.svg','Deepseek.svg','Google Gemini.svg','Google.svg','Google developers.svg','Khan academy.svg','Stack Overflow.svg','Blogger.svg','Wordpress.svg']},
{t:'Navegadores y privacidad',f:['Chrome.svg','Firefox.svg','Brave.svg','Opera.svg','Microsoft Edge.svg','Apple Safari.svg','Duckduckgo.svg','Tor Browser.svg','Tor.svg']}
];
const catLabels={en:['Languages and markup','Databases, search and streaming','Architecture, APIs and methods','Frameworks, APIs and development','DevOps, cloud and repositories','IDEs, engines and editors','Systems, virtualization and terminals','Design, documents, collaboration and office tools','AI, web and resources','Browsers and privacy'],ca:['Llenguatges i marcatge','Bases de dades, cerca i streaming','Arquitectura, APIs i metodologies','Frameworks, APIs i desenvolupament','DevOps, núvol i repositoris','IDEs, motors i editors','Sistemes, virtualització i terminals','Disseny, documentació, col·laboració i ofimàtica','IA, web i recursos','Navegadors i privacitat'],fr:['Langages et balisage','Bases de données, recherche et streaming','Architecture, APIs et méthodes','Frameworks, APIs et développement','DevOps, cloud et dépôts','IDEs, moteurs et éditeurs','Systèmes, virtualisation et terminaux','Design, documentation, collaboration et bureautique','IA, web et ressources','Navigateurs et confidentialité'],de:['Sprachen und Markup','Datenbanken, Suche und Streaming','Architektur, APIs und Methoden','Frameworks, APIs und Entwicklung','DevOps, Cloud und Repositories','IDEs, Engines und Editoren','Systeme, Virtualisierung und Terminals','Design, Dokumentation, Zusammenarbeit und Office-Tools','KI, Web und Ressourcen','Browser und Datenschutz']};
const conceptLabels={en:{'Arquitectura hexagonal':'Hexagonal architecture','Microservicios':'Microservices','Modelo Vista Controlador':'Model View Controller','API REST':'REST API','Scrum':'Scrum'},ca:{'Arquitectura hexagonal':'Arquitectura hexagonal','Microservicios':'Microserveis','Modelo Vista Controlador':'Model Vista Controlador','API REST':'API REST','Scrum':'Scrum'},fr:{'Arquitectura hexagonal':'Architecture hexagonale','Microservicios':'Microservices','Modelo Vista Controlador':'Modèle Vue Contrôleur','API REST':'API REST','Scrum':'Scrum'},de:{'Arquitectura hexagonal':'Hexagonale Architektur','Microservicios':'Microservices','Modelo Vista Controlador':'Model View Controller','API REST':'REST API','Scrum':'Scrum'}};
function skillName(file){return file.replace('.svg','').replace('C# (CSharp)','C#').replace('C++ (CPlusPlus)','C++').replace('PostgresSQL','PostgreSQL').replace('NET core','.NET Core').replace('Claude code','Claude Code').replace('Duckduckgo','DuckDuckGo').replace('Mariadb','MariaDB').replace('Odoo_logo','Odoo').replace('Aws dynamodb','AWS DynamoDB').replace('Aws keyspaces','AWS Keyspaces').replace('Vmware workstation','VMware Workstation').replace('Elastic search','Elasticsearch').replace('Spring boot','Spring Boot')}
function skillSrc(file){return 'Icons/'+encodeURIComponent(file)}
function conceptName(name,lang){return (conceptLabels[lang]&&conceptLabels[lang][name])||name}
function renderSkills(){const root=document.querySelector('#conocimientos');if(!root)return;const lang=document.documentElement.lang||'es';const title=lang==='en'?'Skills':lang==='ca'?'Coneixements':lang==='fr'?'Compétences':lang==='de'?'Kenntnisse':'Conocimientos';root.innerHTML='<div class="section-title"><h2>'+title+'</h2></div><div class="tech-groups skills-from-icons">'+skillGroups.map((g,gi)=>'<div class="tech-group"><h3>'+((catLabels[lang]&&catLabels[lang][gi])||g.t)+'</h3><div class="tech-grid">'+(g.f||[]).map(file=>'<div class="tech-card has-local-icon"><img src="'+skillSrc(file)+'" alt=""><span>'+skillName(file)+'</span></div>').join('')+(g.c||[]).map(item=>'<div class="tech-card has-concept-icon"><strong>'+item[0]+'</strong><span>'+conceptName(item[1],lang)+'</span></div>').join('')+'</div></div>').join('')+'</div>'}
function skillStyle(){if(document.getElementById('skills-local-style'))return;const s=document.createElement('style');s.id='skills-local-style';s.textContent='.tech-card.has-local-icon:before,.tech-card.has-concept-icon:before{display:none!important}.tech-card.has-local-icon,.tech-card.has-concept-icon{font-size:1rem}.tech-card.has-local-icon img{width:2.55rem;height:2.55rem;object-fit:contain}.tech-card.has-concept-icon strong{display:grid;place-items:center;width:2.55rem;height:2.55rem;border:1px solid color-mix(in srgb,var(--text) 18%,transparent);font-size:.78rem;letter-spacing:.05em}.skills-from-icons .tech-grid{grid-template-columns:repeat(auto-fill,minmax(92px,1fr))}';document.head.appendChild(s)}
function initSkillsIcons(){skillStyle();renderSkills();const sel=document.getElementById('languageSelect');if(sel&&!sel.dataset.skillsBound){sel.dataset.skillsBound='true';sel.addEventListener('change',()=>setTimeout(renderSkills,0))}}
if(document.readyState==='loading'){window.addEventListener('DOMContentLoaded',initSkillsIcons,{once:true})}else{initSkillsIcons()}
