var portfolioThemeMode='auto';
var portfolioVisualStyle='classic';
try{portfolioThemeMode=localStorage.getItem('portfolio-theme')||'auto';portfolioVisualStyle=localStorage.getItem('portfolio-visual-style')||'classic'}catch(e){}
function portfolioAutoTheme(){var h=new Date().getHours();return h>=7&&h<20?'light':'dark'}
function portfolioApplyTheme(){var t=portfolioThemeMode==='auto'?portfolioAutoTheme():portfolioThemeMode;document.body.setAttribute('data-theme',t);document.body.setAttribute('data-visual-style',portfolioVisualStyle);var b=document.getElementById('themeButton');if(b)b.textContent=portfolioThemeMode==='auto'?'Auto':portfolioThemeMode==='light'?'Claro':'Oscuro'}
function portfolioThemePanel(){var panel=document.getElementById('themePanel');if(panel)return panel;panel=document.createElement('div');panel.id='themePanel';panel.className='theme-panel';panel.innerHTML='<button type="button" data-style="classic">Clásico<small>Estilo cristal actual</small></button><button type="button" data-style="aurora">Aurora<small>Variante oculta con cristal reforzado</small></button>';document.body.appendChild(panel);panel.addEventListener('click',function(e){var btn=e.target.closest('button[data-style]');if(!btn)return;portfolioVisualStyle=btn.dataset.style;try{localStorage.setItem('portfolio-visual-style',portfolioVisualStyle)}catch(err){}portfolioApplyTheme();portfolioMarkPanel();panel.classList.remove('open')});return panel}
function portfolioMarkPanel(){var panel=document.getElementById('themePanel');if(!panel)return;panel.querySelectorAll('button[data-style]').forEach(function(btn){btn.classList.toggle('active',btn.dataset.style===portfolioVisualStyle)})}
function portfolioToggleThemePanel(){var panel=portfolioThemePanel();portfolioMarkPanel();panel.classList.toggle('open')}
window.addEventListener('DOMContentLoaded',function(){var b=document.getElementById('themeButton');portfolioApplyTheme();if(b)b.addEventListener('click',function(e){if(e.altKey){e.preventDefault();portfolioToggleThemePanel();return}portfolioThemeMode=portfolioThemeMode==='auto'?'light':portfolioThemeMode==='light'?'dark':'auto';try{localStorage.setItem('portfolio-theme',portfolioThemeMode)}catch(err){}portfolioApplyTheme()});document.addEventListener('click',function(e){var panel=document.getElementById('themePanel');if(panel&&panel.classList.contains('open')&&!panel.contains(e.target)&&e.target!==b)panel.classList.remove('open')});var l=document.getElementById('languageSelect');if(l)l.addEventListener('change',function(){document.documentElement.lang=l.value;try{localStorage.setItem('portfolio-language',l.value)}catch(e){}})});
setInterval(function(){if(portfolioThemeMode==='auto')portfolioApplyTheme()},60000);
