const tx={};
const projectText={};
const projectDescriptions={
  es:{tablaElementos:'Tabla periódica ampliada para explorar elementos, espectros atómicos, propiedades, datos científicos y relaciones químicas desde una interfaz interactiva.',orbitalis:'Simulador de cartografía orbital para explorar cuerpos reales del Sistema Solar mediante órbitas configurables, escaneo progresivo, cobertura 3D y mapas de adquisición 2D.'},
  ca:{tablaElementos:'Taula periòdica ampliada per explorar elements, espectres atòmics, propietats, dades científiques i relacions químiques des d’una interfície interactiva.',orbitalis:'Simulador de cartografia orbital per explorar cossos reals del Sistema Solar mitjançant òrbites configurables, escaneig progressiu, cobertura 3D i mapes d’adquisició 2D.'},
  en:{tablaElementos:'Expanded periodic table for exploring elements, atomic spectra, properties, scientific data and chemical relationships from an interactive interface.',orbitalis:'Orbital mapping simulator for exploring real Solar System bodies through configurable orbits, progressive scanning, 3D coverage and 2D acquisition maps.'},
  fr:{tablaElementos:'Table périodique étendue pour explorer éléments, spectres atomiques, propriétés, données scientifiques et relations chimiques depuis une interface interactive.',orbitalis:'Simulateur de cartographie orbitale permettant d’explorer des corps réels du Système solaire grâce à des orbites configurables, un balayage progressif, une couverture 3D et des cartes d’acquisition 2D.'},
  de:{tablaElementos:'Erweiterte Periodentafel zur Erkundung von Elementen, Atomspektren, Eigenschaften, wissenschaftlichen Daten und chemischen Beziehungen in einer interaktiven Oberfläche.',orbitalis:'Orbitaler Kartierungssimulator zur Erkundung realer Himmelskörper des Sonnensystems mit konfigurierbaren Bahnen, progressivem Scan, 3D-Abdeckung und 2D-Erfassungskarten.'},
  pt:{tablaElementos:'Tabela periódica ampliada para explorar elementos, espectros atómicos, propriedades, dados científicos e relações químicas numa interface interativa.',orbitalis:'Simulador de cartografia orbital para explorar corpos reais do Sistema Solar através de órbitas configuráveis, varrimento progressivo, cobertura 3D e mapas de aquisição 2D.'},
  it:{tablaElementos:'Tavola periodica ampliata per esplorare elementi, spettri atomici, proprietà, dati scientifici e relazioni chimiche da un’interfaccia interattiva.',orbitalis:'Simulatore di cartografia orbitale per esplorare corpi reali del Sistema Solare tramite orbite configurabili, scansione progressiva, copertura 3D e mappe di acquisizione 2D.'}
};
function setTextList(selector,items){document.querySelectorAll(selector).forEach((n,i)=>{if(items&&items[i])n.textContent=items[i]})}
function setResumeList(column,items){if(!column||!items)return;column.querySelectorAll('ol>li').forEach((li,i)=>{const data=items[i];if(!data)return;const date=li.querySelector(':scope>span');const title=li.querySelector(':scope>strong');if(date)date.textContent=data[0];if(title)title.textContent=data[1];li.querySelectorAll(':scope>ul>li').forEach((b,j)=>{if(data[2]&&data[2][j])b.textContent=data[2][j]})})}
function setLang(l){const d=tx[l]||tx.es;if(!d)return;document.documentElement.lang=l;try{localStorage.setItem('portfolio-language',l)}catch(e){}setTextList('.nav-links a[href^="#"]',d.nav);const kicker=document.querySelector('.hero-copy .kicker');if(kicker)kicker.textContent=d.kicker;const hero=document.querySelector('.hero-copy p:not(.kicker)');if(hero)hero.textContent=d.hero;['#perfil h2','#valor h2','#proyectos h2','#conocimientos h2','#curriculum h2','#contacto h2'].forEach((s,i)=>{const n=document.querySelector(s);if(n)n.textContent=d.heads[i]});setTextList('#perfil .profile-text p',d.profile);setTextList('#valor .value-grid p',d.value);document.querySelectorAll('.project-card>p').forEach((p,i)=>{if(!p.dataset.es)p.dataset.es=p.textContent;const key=p.dataset.projectKey;if(key&&projectDescriptions[l]&&projectDescriptions[l][key])p.textContent=projectDescriptions[l][key];else if(projectText[l]&&projectText[l][i])p.textContent=projectText[l][i];else if(l==='es')p.textContent=p.dataset.es});document.querySelectorAll('.cv-actions a').forEach((a,i)=>{if(d.cv.buttons[i])a.textContent=d.cv.buttons[i]});const cols=document.querySelectorAll('#curriculum .resume-column');cols.forEach((c,i)=>{const h=c.querySelector('h3');if(h&&d.cv.cols[i])h.textContent=d.cv.cols[i]});setResumeList(cols[0],d.cv.education);setResumeList(cols[1],d.cv.experience);const contact=document.querySelector('#contacto');if(contact){const lead=contact.querySelector('.section-title p');if(lead)lead.textContent=d.contact.lead;contact.querySelectorAll('label').forEach((label,i)=>{if(d.contact.labels[i])label.childNodes[0].nodeValue=d.contact.labels[i]});const subject=contact.querySelector('input[name="asunto"]');if(subject)subject.value=d.contact.subject;const send=contact.querySelector('button[type="submit"]');if(send)send.textContent=d.contact.send}const f=document.querySelector('footer a');if(f)f.textContent=d.top;document.dispatchEvent(new CustomEvent('portfolio-language-change',{detail:{lang:l}}))}
function initCoreI18n(){document.querySelectorAll('.project-card>p').forEach(p=>{if(!p.dataset.es)p.dataset.es=p.textContent});const s=document.getElementById('languageSelect');let saved='es';try{saved=localStorage.getItem('portfolio-language')||'es'}catch(e){}if(s&&tx[saved])s.value=saved;if(s&&!s.dataset.coreBound){s.dataset.coreBound='true';s.addEventListener('change',()=>setLang(s.value))}setLang(s?.value||saved||'es')}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',()=>setTimeout(initCoreI18n,0),{once:true});else setTimeout(initCoreI18n,0);
